language: bash
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libc6-i386
  - npm install
  - npm install -g grunt-cli
  - chmod -R 0777 ./bin && ./bin/amxx-install.sh
script:
  - cd addons/amxmodx/scripting && ./amxxpc -v
