language: bash
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y g++-multilib libc6-dev-i386 lib32stdc++6 lib32z1-dev
  - chmod -R 0777 ./bin
  - ./bin/amxx-install.sh
  - chmod -R 0777 ./build
script:
  - cd build/packages/base/addons/amxmodx/scripting
  - ./amxxpc test.sma
